### ISSUE TITLE
Transitive dependencies not put in the classpath

### ISSUE THREAD

**Issue by JohnnyJayJay** [knightzmc/pdm#12]
With newer versions of PDM, transitive dependencies don't appear to be put into the classpath/resolved anymore.

**Log:** https://pastebin.com/mzbic6L4
**dependencies.json:** https://pastebin.com/XZt3KGVa
**PluginLibraries directory:** 
![](https://i.imgur.com/wU7MjjH.png)

`org.objectweb.asm.commons.Remapper` (coming from `asm-commons`) is a dependency of `compatre`, which in turn is a direct dependency of the plugin and is resolved correctly. 

## Code

```java
@Override
public void onLoad() {
  PluginDependencyManager dependencyManager = new PDMBuilder(this).build();
  dependencyManager.loadAllDependencies().join();
  NmsClassLoader.loadNmsDependents(PresentPlugin.class); // error occurs inside here
}
```

## Steps to reproduce

1. Put this plugin on your server: https://github.com/WeLoveOpenSourcePlugins/presents/releases/tag/v0.2.0
2. Run the server (it may not happen the first time, more on that below)

## System and environment

**Java version:** 12
**Spigot version:** 1.14.4
**PDM version:** 0.0.11 (also happens on 0.0.20)

## Further observations

- This error does not happen when the `PluginLibraries` directory does not exist on start
- It happens regardless of using `PDMBuilder` or `PluginDependencyManager` directly
- The error does not happen on version `0.0.1`

**Comment by knightzmc** [comment]
This should be fixed in 0.0.21
