### ISSUE TITLE
Can't bypass Intrinsics generation

### ISSUE THREAD

**Issue by TheRafaelFarias** [knightzmc/pdm#28]
I was using PDM for the first time, but when compiles Intrinsics verification is generated

I tried using elvis operator with return (Didn't worked) 
I tried executing in init {} (Didn't work too)

What I did was create a Java function to start PDM and then call in Kotlin

The example is using the Elvis operator, but with me didn't work, why? (Kotlin 1.4.10)

**Comment by TheRafaelFarias** [comment]
I created a function in Java to return the PluginDependencyManager and init in Kotlin code. Works too

**Comment by knightzmc** [comment]
The intrinsics generation is patchy at best. The workaround that I find works the best is to do everything in 1 line, without any immediary variables.

**Comment by TheRafaelFarias** [comment]
Using everything in 1 line worked
